# Generated by Django 5.1.4 on 2024-12-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FixedAmountDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.discount')),
                ('amount', models.FloatField()),
            ],
            bases=('discounts.discount',),
        ),
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.discount')),
                ('percentage', models.FloatField(default=0.1)),
            ],
            bases=('discounts.discount',),
        ),
        migrations.CreateModel(
            name='TieredDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discounts.discount')),
            ],
            bases=('discounts.discount',),
        ),
    ]
